"""Hand-ported patterns omitted by the auto-extractor (function replacements, complex regex)."""

from __future__ import annotations

import re
from typing import Any, Dict, List

SUPPLEMENTAL_PATTERN_DEFINITIONS: List[Dict[str, Any]] = [
    {
        "category": "Personal Information",
        "type": "fax_number",
        "regex": r"""\b(?:fax|facsimile|f:)[\s:]*(?:\+\d{1,4}[\s.-]?\(?\d{1,4}\)?[\s.-]?\d{1,4}[\s.-]?\d{1,4}[\s.-]?\d{1,9}|\(\d{3}\)\s?\d{3}[.-]\d{4}|\d{3}[.-]\d{3}[.-]\d{4})\b""",
        "flags": re.IGNORECASE,
        "replacement": "[REDACTED-FAX]",
        "description": "Fax Number — keyword-first format",
        "severity": "high",
        "enabled": True,
    },
    {
        "category": "Financial Information",
        "type": "certificate_license_number",
        "regex": r"""\b(?:certificate|cert|licence|lic)[\s#:]+([A-Z0-9-]{6,20})\b|\blicense[\s#:]+(?![A-Z]{2}-[A-Z]\d)([A-Z0-9-]{6,20})\b""",
        "flags": re.IGNORECASE,
        "replacement": "[REDACTED-CERT]",
        "description": "Certificate/License Numbers",
        "severity": "high",
        "enabled": True,
    },
    {
        "category": "Location Information",
        "type": "city_state_zip_pattern",
        "regex": r"""\b([A-Za-z]+(?:\s+[A-Za-z]+){0,3})\s*,\s*(AL|AK|AZ|AR|CA|CO|CT|DE|FL|GA|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY|DC)\s+(\d{5}(?:-\d{4})?)\b""",
        "flags": re.IGNORECASE,
        "replacement": "[REDACTED-CITY], [REDACTED-STATE] [REDACTED-ZIP]",
        "description": "City, State ZIP",
        "severity": "high",
        "enabled": True,
    },
    {
        "category": "Location Information",
        "type": "city_state_pattern",
        "regex": r"""\b([A-Za-z]+(?:\s+[A-Za-z]+){0,3})\s*,\s*(AL|AK|AZ|AR|CA|CO|CT|DE|FL|GA|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY|DC)\b""",
        "flags": re.IGNORECASE,
        "replacement": "[REDACTED-CITY], [REDACTED-STATE]",
        "description": "City, State without ZIP",
        "severity": "high",
        "enabled": True,
    },
    {
        "category": "Personal Information",
        "type": "person_full_name",
        "regex": r"""\b((?:name|patient|author|physician|doctor|nurse|provider|attending|contact|client|signed\s+by|dictated\s+by|reviewed\s+by|prepared\s+by|verified\s+by|by|from|to|cc|ref)[\s:]+)([A-Z][a-z]+(?:\s+[A-Z][a-z]{2,}){1,2})\b""",
        "flags": re.IGNORECASE,
        "replacement": r"\1[REDACTED-NAME]",
        "description": "Keyword-anchored full person names",
        "severity": "critical",
        "enabled": True,
    },
    {
        "category": "Personal Information",
        "type": "full_name",
        "regex": r"""\b((?:name|patient|author|physician|doctor|nurse|provider|attending|contact|client|signed\s+by|dictated\s+by|reviewed\s+by|prepared\s+by|verified\s+by|by|from|to|cc|ref)[\s:]+)([A-Z][a-z]+ [A-Z][a-z]{2,})\b""",
        "flags": re.IGNORECASE,
        "replacement": r"\1[REDACTED-NAME]",
        "description": "Keyword-anchored two-word names",
        "severity": "high",
        "enabled": True,
    },
    {
        "category": "Personal Information",
        "type": "uppercase_name",
        "regex": r"""\b((?:name|patient|provider|author|signed|dictated|attending|by|from|to)[\s:]+)([A-Z]{4,}(?:\s+[A-Z]{2,})*)\b""",
        "flags": 0,
        "replacement": r"\1[REDACTED-NAME]",
        "description": "Keyword-anchored all-caps names",
        "severity": "critical",
        "enabled": True,
    },
    {
        "category": "Personal Information",
        "type": "standalone_alphanumeric_id",
        "regex": r"""\b(?!\d{3}-\d{3}-\d{4}\b)\d[A-Z0-9]{2,3}-[A-Z0-9]{2,3}-[A-Z0-9]{3,4}\b""",
        "flags": 0,
        "replacement": "[REDACTED-MEMBER-ID]",
        "description": "Formatted alphanumeric member IDs",
        "severity": "critical",
        "enabled": True,
    },
    {
        "category": "Personal Information",
        "type": "orphaned_last_name",
        "regex": r"""\b(?:^|[^\w])([A-Z][a-z]{2,})\s+(?=\[REDACTED(?:-[A-Z0-9]+)+\])""",
        "flags": 0,
        "replacement": "[REDACTED-NAME]",
        "description": "Orphaned first name before redaction token",
        "severity": "critical",
        "enabled": True,
    },
    {
        "category": "Demographics",
        "type": "age_sex_combo",
        "regex": r"""\b(?:\d{1,3}\s*(?:yo|y\.o\.|y/o)\s*(?:male|female|m|f)|(?:male|female)\s+\d{1,3}\s*(?:yo|y\.o\.|y/o))\b""",
        "flags": re.IGNORECASE,
        "replacement": "[REDACTED-AGE] [REDACTED-SEX]",
        "description": "Age and sex combo phrases",
        "severity": "critical",
        "enabled": True,
    },
    {
        "category": "Technical Information",
        "type": "passport_number",
        "regex": r"""\b(?:passport|travel\s*document)[\s#:]*[A-Z]{1,2}\d{6,9}\b""",
        "flags": re.IGNORECASE,
        "replacement": "[REDACTED-PASSPORT]",
        "description": "Passport numbers with keyword context",
        "severity": "critical",
        "enabled": True,
    },
    {
        "category": "Technical Information",
        "type": "drivers_license",
        "regex": r"""\b(?:driver'?s?\s+license|DL|drivers?\s+lic)[\s#:]+([A-Z]{2}-[A-Z]\d{4,8}|[A-Z]\d{6,8}|[A-Z]{1,2}\d{5,7})\b""",
        "flags": re.IGNORECASE,
        "replacement": "[REDACTED-DL]",
        "description": "Driver license numbers",
        "severity": "critical",
        "enabled": True,
    },
    {
        "category": "Technical Information",
        "type": "bare_domain_url",
        "regex": r"""\b(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+(?:com|org|net|edu|gov|io|co|uk|de|fr|au|ca|us|info|biz|me|app|dev|ai)\b""",
        "flags": re.IGNORECASE,
        "replacement": "[REDACTED-URL]",
        "description": "Bare domain names",
        "severity": "medium",
        "enabled": True,
    },
]

SUPPLEMENTAL_PATTERN_COUNT = len(SUPPLEMENTAL_PATTERN_DEFINITIONS)