"""Auto-generated pattern definitions for APXRedactionEngine."""

from __future__ import annotations

import re
from typing import Any, Dict, List

PATTERN_DEFINITIONS: List[Dict[str, Any]] = [
    {
        "category": 'Personal Information',
        "type": 'email_address',
        "regex": r"""\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b""",
        "flags": 0,
        "replacement": '[REDACTED-EMAIL]',
        "description": 'Email Address',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Financial Information',
        "type": 'ssn',
        "regex": r"""\b\d{3}-\d{2}-\d{4}\b|\b(?:SSN|Social Security(?:\s+Number)?|social security(?:\s+number)?)[\s:#]*\d{3}[\s-]\d{2}[\s-]\d{4}\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-SSN]',
        "description": 'Social Security Number (dashes: 123-45-6789, spaces with keyword: SSN 123 45 6789)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Financial Information',
        "type": 'ssn_last4',
        "regex": r"""\b(?:ssn)?_?last_?4[:=]\s*(\d{4})\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-SSN4]',
        "description": 'SSN Last 4 Digits (ssn_last4, last4, etc.)',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Financial Information',
        "type": 'credit_card_dashed',
        "regex": r"""\b(?:4\d{3}-\d{4}-\d{4}-\d{4}|5[1-5]\d{2}-\d{4}-\d{4}-\d{4}|3[47]\d{2}-\d{6}-\d{5})\b""",
        "flags": 0,
        "replacement": '[REDACTED-CC]',
        "description": 'Credit Card Number (with dashes)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Financial Information',
        "type": 'credit_card',
        "regex": r"""\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|6(?:011|5[0-9]{2})[0-9]{12}|(?:2131|1800|35\d{3})\d{11})\b""",
        "flags": 0,
        "replacement": '[REDACTED-CC]',
        "description": 'Credit Card Number (no dashes)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Financial Information',
        "type": 'iban',
        "regex": r"""\b[A-Z]{2}\d{2}(?:\s?[A-Z0-9]{4}){2,7}(?:\s?[A-Z0-9]{1,4})?\b""",
        "flags": 0,
        "replacement": '[REDACTED-IBAN]',
        "description": 'IBAN (International Bank Account Number) - all formats including UK/IE/NL',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Financial Information',
        "type": 'national_id_numbers',
        "regex": r"""(?<!routing[\s:]+)\b(?:[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]|\d{3}\s\d{3}\s\d{3}|\d{1,2}\s\d{2}\s\d{2}\s\d{2,3}\s\d{3}\s\d{3}\s\d{2})\b""",
        "flags": 0,
        "replacement": '[REDACTED-NATIONAL-ID]',
        "description": 'National ID Numbers (Italian Codice Fiscale, French NIR with spaces, Canadian SIN with spaces)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Financial Information',
        "type": 'tax_id',
        "regex": r"""\b(?:EIN|Tax\s*ID|TIN|NI|TFN)[\s#:]*([A-Z0-9-]{2,}-\d{2,}|\d{2}-\d{7}|\d{3}-\d{2}-\d{4}|[A-Z]{2}\d{6,8})\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-TAX-ID]',
        "description": 'Tax/Employer IDs (EIN, TIN, UK NI, AU TFN) with keyword context',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Financial Information',
        "type": 'bank_account',
        "regex": r"""\b\d{4}-\d{4}-\d{4}-\d{4}\b""",
        "flags": 0,
        "replacement": '[REDACTED-BANK]',
        "description": 'Bank Account Number',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Financial Information',
        "type": 'routing_number',
        "regex": r"""\b(?:routing|routing\s*number|routing\s*#|rtn|aba)[\s:]+\d{9}\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-ROUTING]',
        "description": 'Routing Number with banking context prefix',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Financial Information',
        "type": 'credit_card_generic',
        "regex": r"""\b(?:4\d{3}|5[1-5]\d{2}|3[47]\d{2}|6(?:011|5\d{2})|2(?:2(?:2[1-9]|[3-9]\d)|[3-6]\d{2}|7(?:[01]\d|20)))[\s-]?\d{4}[\s-]?\d{4}[\s-]?\d{4}\b""",
        "flags": 0,
        "replacement": '[REDACTED-CC]',
        "description": 'Credit Card Number with valid prefix (Visa 4xxx, MC 51-55/2221-2720, Amex 34/37, Discover 6011/65)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Financial Information',
        "type": 'account_number',
        "regex": r"""\b(?:account|acct|acc?s?|checking|savings)[\s#:]*(\d{8,17})\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-ACCOUNT]',
        "description": 'Bank Account Number near keywords (account 1234567890, acct#123456789)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Financial Information',
        "type": 'cvv',
        "regex": r"""\b(?:cvv|cvc|security\s?code|cid)[\s:]*\d{3,4}\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-CVV]',
        "description": 'CVV/CVC/Security Code (cvv: 123, security code 4567)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Financial Information',
        "type": 'ssn_fragment',
        "regex": r"""\b(?:SSN|Social Security|social security)?\s*(?:ending|last\s*(?:4\s*)?digits?|ends?(?:\s*in)?)\s*(\d{4})\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-SSN4]',
        "description": 'SSN Last 4 Digits fragments (SSN ending 3456, last 4 digits 7890)',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Financial Information',
        "type": 'cc_fragment',
        "regex": r"""\b(?:(?:credit\s*)?card|visa|mastercard|amex|discover)?\s*(?:ending|last\s*(?:4\s*)?digits?|ends?(?:\s*in)?)\s*(\d{4})\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-CC4]',
        "description": 'Credit card last 4 digits fragments (card ending 4112, Visa last 4 5678)',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Financial Information',
        "type": 'crypto_wallet',
        "regex": r"""\b(0x[a-fA-F0-9]{40}|bc1[a-zA-HJ-NP-Z0-9]{25,39}|[13][a-km-zA-HJ-NP-Z1-9]{25,34})\b""",
        "flags": 0,
        "replacement": '[REDACTED-CRYPTO-WALLET]',
        "description": 'Cryptocurrency wallet addresses (Ethereum 0x, Bitcoin bc1/1/3) — exact format only',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'address',
        "regex": r"""(?<!\d{1,2}\.)\b\d{1,5}\s+(?:[A-Za-z]+\s+)*?[A-Za-z]+\s+(?:Street|St|Avenue|Ave|Road|Rd|Boulevard|Blvd|Drive|Dr|Lane|Ln|Court|Ct|Way|Place|Pl|Parkway|Pkwy|Highway|Hwy|Circle|Cir)(?:\s*\.)?(?:,?\s+(?:Apt\.?|Apartment|Suite|Ste\.?|Unit|#)\s*[A-Za-z0-9-]+)?""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-ADDRESS]',
        "description": 'Street Address with any street name — catches "303 birch st", "123 Main Avenue"',
        "severity": 'medium',
        "enabled": True,
    },
    {
        "category": 'Location Information',
        "type": 'city_county_names',
        "regex": r"""\b(New York|Los Angeles|Chicago|Houston|Phoenix|Philadelphia|San Antonio|San Diego|Dallas|San Jose|Austin|Jacksonville|Fort Worth|Columbus|Charlotte|San Francisco|Indianapolis|Seattle|Denver|Washington|Boston|Nashville|Detroit|Portland|Las Vegas|Memphis|Louisville|Baltimore|Milwaukee|Albuquerque|Tucson|Fresno|Sacramento|Kansas City|Atlanta|Raleigh|Miami|Cleveland|Oakland|Minneapolis|Arlington|Tampa|Honolulu|Anaheim|Riverside|Lexington|Pittsburgh|Stockton|Cincinnati|Toledo|Newark|Plano|Henderson|Lincoln|Buffalo|Orlando|Chandler|Norfolk|Durham|Madison|Lubbock|Garland|Reno|Irvine|Chesapeake|Irving|Scottsdale|Fremont|Gilbert|Boise|Richmond|Spokane|Des Moines|Tacoma|Birmingham|Huntsville|Springfield|Salt Lake City|Grand Rapids|Tallahassee|Worcester|Knoxville|Mobile|Shreveport|Augusta|Amarillo|Little Rock|Akron|Corpus Christi|Bakersfield|Anchorage|Tulsa|Wichita|Omaha|Virginia Beach|Long Beach|Colorado Springs|Huntington Beach|Glendale|Santa Ana|Grand Prairie|Brownsville|Montgomery|Modesto|Sioux Falls|Fayetteville|Asheville|Ashland|Cambridge|Quincy|Dorchester|Brookline|Somerville|Medford|Newton|Belmont|Watertown|Waltham|Malden|Everett|Revere|Chelsea|Winthrop|Dedham|Needham|Wellesley|Framingham|Natick|Weston|Winchester|Woburn|Burlington|Bedford|Concord|Sudbury|Wayland|Hopkinton|Marlborough|Hudson|Acton|Maynard|Stow|Boxborough|Fort Wayne|Jersey City|Chula Vista|North Las Vegas|Greensboro|Rochester|Winston-Salem|Hialeah|Garland|Glendale|Scottsdale|Baton Rouge|Fremont|San Bernardino|Richmond|Boise City|Spokane|Des Moines|Tacoma|Modesto|Fontana|Santa Clarita|Birmingham|Oxnard|Fayetteville|Moreno Valley|Huntington Beach|Yonkers|Aurora|Montgomery|Amarillo|Little Rock|Akron|Augusta|Shreveport|Mobile|Grand Rapids|Salt Lake City|Tallahassee|Huntsville|Grand Prairie|Knoxville|Worcester|Newport News|Brownsville|Santa Rosa|Port St Lucie|Chattanooga|Providence|Fort Lauderdale|Tempe|Oceanside|Garden Grove|Rancho Cucamonga|Cape Coral|Santa Clara|Vancouver|Sioux Falls|Ontario|McKinney|Elk Grove|Pembroke Pines|Salem|Eugene|Lancaster|Corona|Palmdale|Salinas|Springfield|Pasadena|Fort Collins|Hayward|Pomona|Joliet|Paterson|Kansas City|Torrance|Sunnyvale|Rockford|Lakewood|Hollywood|Escondido|Clarksville|Alexandria|Naperville|Mesquite|Hampton|Savannah|Orange|Fullerton|Lakewood|McAllen|Miramar|Killeen|Bellevue|Peoria|Murfreesboro|Midland|Frisco|Waco|Denton|Carrollton|Olathe|Surprise|Charleston|Visalia|Roseville|Thornton|Beaumont|Allentown|Evansville|Abilene|Concord|Norman|Berkeley|Round Rock|Billings|Manchester|Ann Arbor|Rochester|Independence|Provo|Odessa|Wilmington|West Valley City|High Point|Carlsbad|Fairfield|Richardson|Murrieta|Burbank|West Jordan|Columbia|Palm Bay|Sterling Heights|New Haven|West Covina|Boulder|El Monte|Cary|Waterbury|Costa Mesa|Pompano Beach|Inglewood|West Palm Beach|Arvada|Miami Gardens|Downey|Elizabeth|Pueblo|College Station|Sandy Springs|Gresham|Temecula|Lewisville|Clearwater|Centennial|Westminster|Elgin|Tyler|Lowell|Daly City|Athens|Springfield|Victorville|Wichita Falls|Allen|El Cajon|Las Cruces|Ventura|Rialto|Dayton|Jurupa Valley|Everett|Bend|Menifee|Sandy|Hillsboro|Antioch|Vista|Rio Rancho|Broken Arrow|Flint|Fargo|Compton|Kennewick|Quincy|South Bend|Vacaville|Davenport|San Mateo|Brockton|Kenosha|Edinburg|Albany|Green Bay|Renton|San Angelo|Concord|Norwalk|Federal Way|Dearborn|South Gate|Tuscaloosa|Sparks|Palm Coast|Plantation|Waukegan|Champaign|Bloomington|Hesperia|West Haven|Sunrise|Longmont|Tuscaloosa|Alhambra|Redding|San Leandro|Trenton|Livermore|Lee Summit|Lawton|Pearland|Gary|Whittier|Redwood City|Santa Maria|Mesquite|Macon|Mission Viejo|Lake Forest|Tracy|Eau Claire|Chico|Hendersonville|Racine|Indio|Mountain View|Nampa|Cranston|Greeley|Bellingham|Iowa City|Burbank|Yakima|Orem|Laredo|Hammond|Gastonia|Newton|Brooklyn Park|Longview|Roswell|Lauderhill|Warwick|Gulfport|Simi Valley|Danbury|Conway|Meridian|Spokane Valley|Lawrence|Pawtucket|Odessa|Lake Charles|Cedar Rapids|Boynton Beach|Syracuse|Carmel|Warner Robins|Turlock|Baldwin Park|Decatur|Vineland|Asheville|Melbourne|Napa|Livonia|Fishers|Redondo Beach|New Braunfels|Manteca|Edinburg|Baytown|Albany|Carson|Greenville|Hammond|Lakeland|Waterloo|Sioux City|Bismarck|Kennewick|Lynwood|Wyoming|Fort Smith|Lynn|Chino|Palo Alto|Burleson|Newton|Rowlett|Franklin|Gaithersburg|Suffolk|Mount Vernon|Plymouth|Davie|Danbury|Parker|Wyoming|Jonesboro|Bellflower|Encinitas|Duluth|Union City|Camarillo|San Marcos|Minnetonka|Clovis|Milpitas|Passaic|Walnut Creek|Yuma|Palatine|Taylorsville|Cathedral City|Deltona|Brentwood|Delray Beach|League City|Coral Gables|Fort Myers|Perris|Clifton|Bowling Green|Taylorsville|Murray|Westland|Bend|Wyoming|Bellingham|Santa Cruz|Lake Elsinore|South Jordan|Sugar Land|Charleston|Berwyn|Berkeley|Deerfield Beach|Wilson|Conway)\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-CITY]',
        "description": 'Top 500 US cities — fallback for standalone city mentions',
        "severity": 'medium',
        "enabled": True,
    },
    {
        "category": 'Location Information',
        "type": 'po_box',
        "regex": r"""\b(?:P\.?\s?O\.?|Post Office)\s*Box\s+\d+\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-POBOX]',
        "description": 'PO Box addresses (PO Box 123, P.O. Box 456)',
        "severity": 'medium',
        "enabled": True,
    },
    {
        "category": 'Location Information',
        "type": 'state_abbreviation',
        "regex": r"""(?<=,\s*|\s+)\b(AL|AK|AZ|AR|CA|CO|CT|DE|FL|GA|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY|DC)\b(?=\s+\d{5}|\s*$|[,\s])""",
        "flags": 0,
        "replacement": '[REDACTED-STATE]',
        "description": 'US State abbreviations in address context — uppercase only',
        "severity": 'medium',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'zip_code',
        "regex": r"""(?<![:\d/\-a-zA-Z])\b\d{5}(?:-\d{4})?\b(?![:\d/\-a-zA-Z])""",
        "flags": 0,
        "replacement": '[REDACTED-ZIP]',
        "description": 'ZIP Code (excludes API paths, product codes, technical IDs, UUIDs)',
        "severity": 'medium',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'month_abbrev_in_context',
        "regex": r"""\b(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\s*\d{1,2}\s*,?\s*\d{4}""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-DATE]',
        "description": 'Month abbreviation with day and year (jan07, 2016)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'embedded_date_concat',
        "regex": r"""\b[a-z]+\d{1,2}(?:january|february|march|april|may|june|july|august|september|october|november|december)\d{4}\d{1,2}:\d{2}(?:est|edt|pst|pdt|cst|cdt)?\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-NAME-DATE]',
        "description": 'Concatenated name+day+month+year+time (e.g., JohnDoe14february201623:14est)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'date_of_birth',
        "regex": r"""\b(?:DOB:?\s*)?(?:(0?[1-9]|1[0-2])/(0?[1-9]|[12]\d|3[01])/\d{4}|\d{4}-(0?[1-9]|1[0-2])-(0?[1-9]|[12]\d|3[01])|(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+(0?[1-9]|[12]\d|3[01]),?\s+\d{4}|(0?[1-9]|[12]\d|3[01])\s+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+\d{4})\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-DOB]',
        "description": 'Date of Birth (MM/DD/YYYY, YYYY-MM-DD, text dates, DOB: prefix)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'partial_dob',
        "regex": r"""\b(?:DOB:?\s*)?(?:(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+(0?[1-9]|[12]\d|3[01])(?!,?\s*\d{4})|(0?[1-9]|1[0-2])/(0?[1-9]|[12]\d|3[01])(?!/\d{4}))\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-DOB]',
        "description": 'Partial Date of Birth (standalone month+day without year)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'mrn',
        "regex": r"""\bMRN[-\s]?\d{4,10}\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-MRN]',
        "description": 'Medical Record Number (MRN-XXXXXX, MRN XXXXXX, MRNXXXXXX)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'birth_year',
        "regex": r"""\b(?:DOB|birth|born|age|dob)[\s:]+\s*(19[0-9]{2}|20[0-2][0-9])\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-YEAR]',
        "description": 'Birth Year with context (DOB, birth, born, age prefix)',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'date_spelled_month_with_year',
        "regex": r"""\b(?:january|february|march|april|may|june|july|august|september|october|november|december)\s+\d{1,2}(?:st|nd|rd|th)?,?\s+\d{4}\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-DATE]',
        "description": 'Date with spelled month and year (January 5th, 2025)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'date_spelled_month_noyear',
        "regex": r"""\b(?:january|february|march|april|may|june|july|august|september|october|november|december)\s+\d{1,2}(?:st|nd|rd|th)?\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-DATE]',
        "description": 'Date with spelled month without year (January 5th, february 24th)',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'date_spelled_month_day_first',
        "regex": r"""\b\d{1,2}(?:st|nd|rd|th)?\s+(?:of\s+)?(?:january|february|march|april|may|june|july|august|september|october|november|december)(?:\s+\d{4})?\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-DATE]',
        "description": 'Date with day first (5th of January, 24 February 2024)',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'any_date_slash',
        "regex": r"""\b\d{1,2}/\d{1,2}/\d{2,4}\b""",
        "flags": 0,
        "replacement": '[REDACTED-DATE]',
        "description": 'Any date with slashes (MM/DD/YYYY, DD/MM/YY)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'any_date_dash',
        "regex": r"""\b\d{4}-\d{1,2}-\d{1,2}\b""",
        "flags": 0,
        "replacement": '[REDACTED-DATE]',
        "description": 'Any date with dashes (YYYY-MM-DD)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'date_dash_mdy',
        "regex": r"""\b\d{2}-\d{2}-\d{4}\b""",
        "flags": 0,
        "replacement": '[REDACTED-DATE]',
        "description": 'Date MM-DD-YYYY with dashes',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'name_with_credential',
        "regex": r"""\b[a-z]{3,}[a-z]{3,}(?:\s*,\s*(?:md|phd|pharmd|rn|np|pa|do|dds|dvm|pharmd|edd|psyd|lcsw|lmft|lpc|cpa|esq|jd|mba)\b)""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-NAME]',
        "description": 'Names with professional credentials (johndoe, md)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'lowercase_name_credential',
        "regex": r"""\b[A-Z][a-z]{2,}(?:\s*,\s*(?:md|phd|pharmd|rn|np|pa|do|dds|dvm|edd|psyd|lcsw|lmft|lpc|cpa|esq|jd|mba)\b)""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-NAME]',
        "description": 'Title case names with credentials (Alice, pharmd)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'concatenated_name_suffix',
        "regex": r"""\b(?:addendum|note|by|signed|prepared|reviewed|dictated|transcribed|verified|approved)by[a-z]{4,}""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-NAME]',
        "description": 'OCR-concatenated names (addendumbyjohndoe)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'policy_member_id',
        "regex": r"""\b(?:plan|policy|member|subscriber|group)[\s#:]+([A-Z0-9-]{6,20})\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-MEMBER-ID]',
        "description": 'Policy/member/subscriber ID numbers (policy: HP987654321, member# ABC123) — applies to insurance, telecom, SaaS, HR',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'member_id_formatted',
        "regex": r"""\b(?:member|policy|account|subscriber)\s+(?:id|number|#|no\.?)[\s:]*([A-Z0-9]{3,4}-[A-Z0-9]{2,4}-[A-Z0-9]{3,5})\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-MEMBER-ID]',
        "description": 'Formatted member/account/subscriber ID (Member ID: 4EG7-XY9-KL2M) — applies to any membership or subscription system',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'name_after_title',
        "regex": r"""\b(?:dr\.?|doctor|prof\.?|professor|rev\.?|hon\.?)\s+[A-Za-z]+(?:\s+[A-Za-z]\.)?(?:\s+[A-Za-z]+)?\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-NAME]',
        "description": 'Name after universal titles (Dr., Prof., Rev., Hon.) — handles middle initials (e.g. Dr. James R. Okafor)',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'embedded_name_date',
        "regex": r"""\b([a-z]{2,})(?:pon|on)\d{1,2}(?:january|february|march|april|may|june|july|august|september|october|november|december)\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-NAME-DATE]',
        "description": 'Embedded name+date concatenation patterns',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Demographics',
        "type": 'age_pattern',
        "regex": r"""\b(\d{1,3})\s*(?:-?\s*)?(years?\s*old|year-old|years?|yo|y\.o\.|y/o)\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-AGE]',
        "description": 'Age in various formats (45 yo, 32 years old, 7 y.o.)',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Demographics',
        "type": 'age_prefix',
        "regex": r"""\b(?:age|aged)[\s:]+(\d{1,3})\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-AGE]',
        "description": 'Age with prefix (age: 21, aged 45)',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Demographics',
        "type": 'age_compressed',
        "regex": r"""\b(\d{1,2})\s*y\s*m(?:\s|[a-z])""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-AGE]',
        "description": 'Compressed age format: "20 y m" (age year male/month)',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Location Information',
        "type": 'ip_address',
        "regex": r"""\b(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]?|0)\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]?|0)\b""",
        "flags": 0,
        "replacement": '[REDACTED-IP]',
        "description": 'IP Address (valid range 0-255 per octet)',
        "severity": 'medium',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'vehicle_vin',
        "regex": r"""\b(?:VIN|vehicle\s+(?:id(?:entification)?|number))[\s#:]+([A-HJ-NPR-Z0-9]{17})\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-VIN]',
        "description": 'Vehicle Identification Number (VIN) with context — 17 characters',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'vehicle_license_plate',
        "regex": r"""\b(?:plate|license plate|tag)[\s#:]+([A-Z0-9-]{2,8})\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-PLATE]',
        "description": 'Vehicle License Plate (plate: ABC1234, tag#XYZ789)',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Technical Information',
        "type": 'mac_address',
        "regex": r"""\b([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})\b""",
        "flags": 0,
        "replacement": '[REDACTED-MAC]',
        "description": 'MAC Address (00:1A:2B:3C:4D:5E or AA-BB-CC-DD-EE-FF)',
        "severity": 'medium',
        "enabled": True,
    },
    {
        "category": 'Technical Information',
        "type": 'web_url',
        "regex": r"""\b(?:https?://|www\.)[-A-Za-z0-9+&@#/%?=~_|!:,.;]*[-A-Za-z0-9+&@#/%=~_|]""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-URL]',
        "description": 'Web URLs (http://, https://, www.)',
        "severity": 'medium',
        "enabled": True,
    },
    {
        "category": 'Technical Information',
        "type": 'tracking_token',
        "regex": r"""\b(?:session|cookie|track|utm|ref|analytics)[\s=:]*[a-zA-Z0-9]{20,}\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-TRACK-TOKEN]',
        "description": 'Session/cookie/tracking/UTM tokens (20+ alphanumeric chars) with keyword',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Technical Information',
        "type": 'photo_image_reference',
        "regex": r"""\b(?:(?:photo|image|picture|img|jpeg|jpg|png|gif|bmp|tiff|pdf)[/\\\s:]+)?[A-Za-z0-9_\-]+\.(?:jpg|jpeg|png|gif|bmp|tiff|pdf)\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-IMAGE]',
        "description": 'Photo/Image file references (patient001.jpg, img/face_scan.png)',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Technical Information',
        "type": 'device_serial_number',
        "regex": r"""\b(?:medical|patient|hospital|clinical|diagnostic|therapeutic|implant|device|equipment|monitor|pump|ventilator)\s+(?:serial|s/n|sn|device|equipment)[\s#:]+([A-Z0-9-]{6,20})\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-SERIAL]',
        "description": 'Medical Device/Equipment Serial Numbers (with medical-device noun prefix)',
        "severity": 'medium',
        "enabled": True,
    },
    {
        "category": 'Technical Information',
        "type": 'biometric_identifiers',
        "regex": r"""\b(?:fingerprint|voiceprint|retina|iris|facial recognition|biometric|palm print|hand geometry|dna profile)[\s:]*(?:scan|id|profile|data|match)?[\s:]*([A-Z0-9-]{6,})?\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-BIOMETRIC]',
        "description": 'Biometric identifiers (fingerprint id: FP-987654, Fingerprint FP-99887766, VOICE-77441122)',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'genetic_marker',
        "regex": r"""\b(BRCA[12]|TP53|EGFR|KRAS|BRAF|MLH1|MSH[26]|PMS2|APC|PTEN|ATM|CHEK2|PALB2|RAD51[CD]?|STK11|CDH1|VHL|RET|MEN1|NF[12]|TSC[12]|MUTYH|HER2|ERBB2|PIK3CA|CDKN2A)(?:\s+(?:variant|mutation|deletion|insertion|amplification|positive|negative|status|gene|allele|pathogenic|benign|VUS|carrier|c\.\S+|p\.\S+|exon\s+\d+))?\b""",
        "flags": 0,
        "replacement": '[REDACTED-GENETIC-MARKER]',
        "description": 'Genetic marker / gene variant (BRCA1, TP53 mutation, EGFR variant) — HIPAA Safe Harbor genomic identifiers',
        "severity": 'critical',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'password',
        "regex": r"""\b(?=[A-Za-z\d@$!%*?&]{8,}\b)(?=[^a-z]*[a-z])(?=[^A-Z]*[A-Z])(?=[^\d]*\d)[A-Za-z\d@$!%*?&]{8,}\b""",
        "flags": 0,
        "replacement": '[REDACTED-PASSWORD]',
        "description": 'Password (complex patterns only)',
        "severity": 'critical',
        "enabled": False,
    },
    {
        "category": 'Personal Information',
        "type": 'phone_number',
        "regex": r"""(?:\+\d{1,4}[\s.-]?\(?\d{1,4}\)?[\s.-]?\d{1,4}[\s.-]?\d{1,4}[\s.-]?\d{1,9}|\(\d{3}\)\s?\d{3}[.\- ]\d{4}|\b\d{3}[.\- ]\d{3}[.\- ]\d{4}\b)""",
        "flags": 0,
        "replacement": '[REDACTED-PHONE]',
        "description": 'Phone Number (international with +, US formats)',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'standalone_number_20_digits',
        "regex": r"""\b\d{20}\b""",
        "flags": 0,
        "replacement": '[REDACTED-NUMBER-20-DIGITS]',
        "description": 'Standalone 20-digit number (tracking, account, or ID)',
        "severity": 'medium',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'standalone_number_12_digits',
        "regex": r"""\b\d{12}\b""",
        "flags": 0,
        "replacement": '[REDACTED-NUMBER-12-DIGITS]',
        "description": 'Standalone 12-digit number (account or ID)',
        "severity": 'medium',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'standalone_number_10_digits',
        "regex": r"""\b\d{10}\b""",
        "flags": 0,
        "replacement": '[REDACTED-NUMBER-10-DIGITS]',
        "description": 'Standalone 10-digit number (likely phone or account)',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'standalone_number_9_digits',
        "regex": r"""\b\d{9}\b""",
        "flags": 0,
        "replacement": '[REDACTED-NUMBER-9-DIGITS]',
        "description": 'Standalone 9-digit number (likely SSN or insurance ID)',
        "severity": 'high',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'standalone_number_8_digits',
        "regex": r"""\b\d{8}\b""",
        "flags": 0,
        "replacement": '[REDACTED-NUMBER-8-DIGITS]',
        "description": 'Standalone 8-digit number (account or member ID)',
        "severity": 'medium',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'standalone_number_7_digits',
        "regex": r"""\b\d{7}\b""",
        "flags": 0,
        "replacement": '[REDACTED-NUMBER-7-DIGITS]',
        "description": 'Standalone 7-digit number (MRN or ID)',
        "severity": 'medium',
        "enabled": True,
    },
    {
        "category": 'Personal Information',
        "type": 'standalone_number_6_digits',
        "regex": r"""\b\d{6}\b""",
        "flags": 0,
        "replacement": '[REDACTED-NUMBER-6-DIGITS]',
        "description": 'Standalone 6-digit number — disabled: fires on timestamps, ZIPs, report codes',
        "severity": 'low',
        "enabled": False,
    },
    {
        "category": 'Location Information',
        "type": 'gps_coordinates',
        "regex": r"""\b([-+]?(?:[0-8]?\d\.\d{4,8}|90\.0{4,8}))\s*,\s*([-+]?(?:1[0-7]\d\.\d{4,8}|[0-9]?\d\.\d{4,8}|180\.0{4,8}))\b""",
        "flags": re.IGNORECASE,
        "replacement": '[REDACTED-GPS]',
        "description": 'GPS Coordinates (requires 4+ decimal places to avoid date/measurement conflicts)',
        "severity": 'medium',
        "enabled": True,
    },
]

PATTERN_COUNT = 63
